### ISSUE TITLE
NOOP SHOULD accept parameters

### ISSUE THREAD

**Issue by Varbin** [aio-libs/aiosmtpd#107]
As stated in RFC 5321 $4.1.1.9 (https://tools.ietf.org/html/rfc5321#section-4.1.1.9) SMTP servers SHOULD ignore arguments, currently aiosmtpd returns an error (Python's smtpd does this, too).

Shall I write a pull request?

**Comment by Mortal** [comment]
I'd say go ahead and send a pull request since it's a bug with RFC compliance.

Fun fact: In RFC 821, NOOP was a command with no arguments, so the smtpd behavior was correct back when it was [added to the standard library in January 2001](https://github.com/python/cpython/commit/7e0d9563caf0eda8b5d76a3bdf24a318f6d592ec) since [RFC 2821](https://tools.ietf.org/html/rfc2821), which changed NOOP to specify that arguments SHOULD be ignored, didn't come out until April 2001.
