### ISSUE TITLE
Documentation Link **WRONG**

### ISSUE THREAD

**Issue by teward** [aio-libs/aiosmtpd#175]
You provide a link to RTD documentation in your README where ideally this would be documented.  **However**, this link is wrong and we instead have to delve in the source code to read your documentation here.

Consider **removing** the RTD link if you have no intention to put your documentation up there.  And inform the Python project as well, because they are linking to the nonexistent documentation in their API.

**Comment by waynew** [comment]
I'm pretty confused. https://aiosmtpd.readthedocs.io/en/latest/ is the link to RTD (indeed, search Google.com for "aiosmtpd docs", which is also where I go when I click on the link in the Readme)

How are you getting there? Are you behind a proxy? I've met really stupid proxies that block documentation because they're "technical".

**Comment by teward** [comment]
At the time of this bug being filed, the `/` URI for the RTD page was NOT redirecting to `/en/latest/` and instead returned a "No content here!" notice.  This has since been changed and is no longer an issue.  (This said, it would be nice to include examples in the RTD documentation for implementations, but that's a different issue)

**Comment by waynew** [comment]
Was probably a bug in RTD 😝
