### ISSUE TITLE
Controller does not pass host name to the protocol

### ISSUE THREAD

**Issue by agronholm** [aio-libs/aiosmtpd#178]
The default implementation of `connection.factory()` does not pass the `hostname` argument to `SMTP()`. Because of this, `SMTP.__init__()` looks up the FQDN of the socket which, at least on my system, takes several seconds **during which the event loop is blocked**. Such a blocking operation should never be executed in the event loop thread.

**Comment by waynew** [comment]
Thanks for the report @agronholm!

Looks like the failure is on this line here:

https://github.com/aio-libs/aiosmtpd/blob/ec804d9038989b20d2068ab3dc69ff0888a48257/aiosmtpd/controller.py#L32

**Comment by agronholm** [comment]
This is the real problem though: https://github.com/aio-libs/aiosmtpd/blob/master/aiosmtpd/smtp.py#L94

I stumbled onto this because in my test runs, it always took suspiciously long for the SMTP server to respond. I traced the problem to the line above. I would recommend using `socket.gethostname()` instead if it has to happen in `SMTP.__init__()`. At least on my system, it gives the same result but returns instantly, unlike `socket.getfqdn()`.

**Comment by waynew** [comment]
That's probably because you don't have a resolvable FQDN - https://stackoverflow.com/a/13932042/344286

I'm pretty sure that simply passing the hostname through should do the correct thing here.

**Comment by v7a** [comment]
I had the same performance issues as Alex and fixed it by inheriting from the controller and overriding `factory()`:
```py
def factory(self):
    return Server(self.handler, hostname=self.hostname, enable_SMTPUTF8=self.enable_SMTPUTF8)
```
Pretty much the same is present in https://github.com/cole/aiosmtplib, in which the `SMTPConnection` class queries the FQDN when issuing a `helo` command. This can be fixed by querying the FQDN once beforehand and passing it as `source_address` upon construction `SMTPConnection` or a subclass thereof (e.g. `aiosmtplib.smtp.SMTP`).

**Comment by pepoluan** [comment]
IMHO the solution suggested by @v7a is correct. If we already pass an explicit hostname to `Controller`, we should pass that as well to `SMTP` in `factory`.

I'm tempted to put this into PR #192 , but that PR is already so unwieldy so I'll defer until the PR is merged, then start a new PR to fix this.

**Comment by pepoluan** [comment]
I accidentally implemented a way of passing through parameters to the `SMTP` class in 7289e6d because a need arose...

It's part of that honkin' huge PR #192 , though 😅

**Comment by pepoluan** [comment]
@v7a w.r.t. this:

> SMTP requires us to use the FQDN for helo/ehlo (given I interpreted https://www.ietf.org/rfc/rfc2821.txt correctly), so passing hostname=self.hostname in factory() is wrong in my eyes.

I've just read RFC2821, and in [Section 3.6](https://tools.ietf.org/html/rfc2821#section-3.6) it says:

> Only resolvable, fully-qualified, domain names (FQDNs) are permitted when domain names are used in SMTP.  In other words, names that can be resolved to MX RRs or A RRs (as discussed in section 5) are permitted, as are CNAME RRs whose targets can be resolved, in turn, to MX or A RRs.

Which I take to mean that "we can use anything as long as it's FQDN _and_ resolvable to A or MX".

So there is no requirement that the domain being returned must be "the actual FQDN of the SMTP Server's interface"; just that whatever it is returning must be resolvable.

There are 2 possible options going forward:

1. We can validate hostname as given by user, and reject if it's not resolvable to A or MX; or
2. We will just assume user is a consenting adult who knows how to read the manuals, and raise a `warn` if user provides a hostname (instead of leaving it `None`)

I am heavily for option No. 2 there.

**Comment by pepoluan** [comment]
With the merging of #202 into 1.3.0, `Controller` now has a special parameter `server_hostname` that gets passed to `SMTP(hostname=...)`

There is a second, submarine issue being discussed here, and that is the behavior of `SMTP` when not given the `hostname` parameter.

Because that's actually a separate issue from "Controller not passing hostname to SMTP", I recommend to start a new issue to discuss that.

In the meanwhilst, I'll close this issue because the main problem -- the title of this Issue -- already has a workaround in 1.3.0. Feel free to reopen this issue if you think it's not yet solved.
