### ISSUE TITLE
Receive email from domain like gmail, yahoo etc

### ISSUE THREAD

**Issue by blob84** [aio-libs/aiosmtpd#187]
Hello I tried to set up a mail server with this module.
The server is able to receive email from a python script from remote, but it doesn't receive email when the sender is an email from gmail or similar.
I have set the noip domain and the mx recorde itself.

**Comment by waynew** [comment]
By default, gmail or yahoo will use your MX record, and port 25. I know for a fact this works, because I get emails all the time myself.

My guess is that your ISP (especially if it's Cox) is blocking port 25. Or it could be your firewall. There are a number of reasons that other providers could not get email to you, but it's definitely not aiosmtpd that's the problem.

**Comment by blob84** [comment]
Thank you for your response. The port 25 is opened, the mail server is an amazon aws machine with ubuntu linux, it was running postfix.

**Comment by blob84** [comment]
When I send an email what is the user I should use, for example my domain is mydomain.biz and the mx record is mail.mydomain.biz, can I send an email to user@mydomain.biz?

**Comment by blob84** [comment]
OK it works, it was a problem with the hostname.
