### ISSUE TITLE
smtpd may be removed from the Python 3.11 standard library

### ISSUE THREAD

**Issue by vstinner** [aio-libs/aiosmtpd#291]
FYI I plan to remove the smtpd module from the Python 3.11 standard library. In my change, I suggest to replace smtpd with aiosmtpd ;-)

* https://bugs.python.org/issue28533
* https://mail.python.org/archives/list/python-dev@python.org/thread/LZOOLX5EKOITW55TW7JQYKLXJUPCAJB4/

**Comment by Karlson2k** [comment]
@vstinner Luckily removal was not approved as [aiosmtpd](https://github.com/aio-libs/aiosmtpd) is not yet ported even to Python 3.10. 
In current situation removal of `smtpd` would remove important functionality from Python without any replacement.

**Comment by vstinner** [comment]
The removal will likely happen in Python 3.12.

**Comment by Karlson2k** [comment]
So SMTP server functionality is planned to be removed from Python without any replacement?

**Comment by waynew** [comment]
I guess we should start getting aiosmtpd working well under more modern Python 😅

**Comment by vstinner** [comment]
> So SMTP server functionality is planned to be removed from Python without any replacement?

One replacement is aiosmtpd, but there are other SMTP servers implemented in Python or not ;-)

**Comment by Karlson2k** [comment]
> I guess we should start getting aiosmtpd working well under more modern Python 😅

@waynew This would be nice. Some distributions soon will switch to Python 3.10 and we will lost SMTP server functionality.

**Comment by wevsty** [comment]
Anyway, there is still a lot of work to be done before replacing smtpd.

**Comment by pepoluan** [comment]
> There is [no single commit in aiosmtpd repo](https://github.com/aio-libs/aiosmtpd/commits/master) for more than last 14 months. Chances that compatibility will be checked (and fixed) before Python 3.11 release are quite low.

Just for an update:

PR #309 and PR #314 enables testing to run successfully on 3.10 and 3.11 after some fixing of GitHub CI in PR #324 

The results of latest tests by GitHub CI are all green as can be seen [here](https://github.com/aio-libs/aiosmtpd/actions/runs/3710376932), [here](https://github.com/aio-libs/aiosmtpd/actions/runs/3710650629), and [here](https://github.com/aio-libs/aiosmtpd/actions/runs/3710700260).

I think those are enough to verify compatibility with Python 3.11.

Besides, Python 3.11 is released anyways, so I think I'll close this issue because it's no longer relevant.

(Still relevant if we're talking about taking out smtpd in Python 3.12, but let's start a new Issue)
