### ISSUE TITLE
Proxy not forwarding messages

### ISSUE THREAD

**Issue by diogo-fernan** [aio-libs/aiosmtpd#65]
Not sure if this is a bug or not, but would appreciate feedback on the following Stack Overflow thread:

http://stackoverflow.com/questions/43278998/python-3-smtp-aiosmtpd-proxy-relay

Thanks.

**Comment by magnus-lycka** [comment]
There seems to be several bugs in the Proxy handler.

handle_DATA seems to assume that envelope is a (unicode) string, but it's actually a bytes object.

_deliver contains log.exception('got', e.__class__) as if you could use the same parameters as in print(), instead of log.exception('got %s', e.__class__)

My quick fix was as below:
```
20d19
< EMPTYSTRING = ''
101c100
<             if NLCRE.match(line):
---
>             if NLCRE.match(line.decode('ascii')):
105,106c104,105
<         lines.insert(i, 'X-Peer: %s%s' % (session.peer[0], ending))
<         data = EMPTYSTRING.join(lines)
---
>         lines.insert(i, b'X-Peer: %s%s' % (session.peer[0].encode('ascii'), ending))
>         data = b''.join(lines)
```

**Comment by Mortal** [comment]
I've [answered](https://stackoverflow.com/a/43639097/1570972) your SO post and opened PR #74.

**Comment by diogo-fernan** [comment]
Your solution does seem to sort out the issue.
Thanks!
